### ISSUE TITLE
TypeError: cannot set 'forward' attribute of immutable type 'type'

### ISSUE THREAD

**Issue by Jamrainbow** [LiewFeng/TeaCache#11]
when i run the eval_teacache_slow func,i met the following error:
Traceback (most recent call last):
  File "/home/workspace/TeaCache/eval/teacache/experiments/opensora.py", line 257, in <module>
    eval_teacache_slow(prompt_list)
  File "/home/workspace/TeaCache/eval/teacache/experiments/opensora.py", line 233, in eval_teacache_slow
    engine.driver_worker.transformer.__class__.__class__.forward = teacache_forward
TypeError: cannot set 'forward' attribute of immutable type 'type'
![image](https://github.com/user-attachments/assets/5a5539f3-8091-4e4e-a9e1-a817bdf4d829)

my env is 
python3.10.12
torch2.2.2
cuda 12.4

my env is below in detail
Package                           Version             Editable project location
--------------------------------- ------------------- ---------------------------
absl-py                           2.1.0
accelerate                        0.34.2
addict                            2.4.0
aiofiles                          23.2.1
aiohttp                           3.9.1
aiosignal                         1.3.1
altair                            5.3.0
annotated-types                   0.6.0
antlr4-python3-runtime            4.9.3
anyio                             4.3.0
anykeystore                       0.2
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
asttokens                         2.4.1
astunparse                        1.6.3
async-timeout                     4.0.3
attrs                             23.2.0
audioread                         3.0.1
av                                12.3.0
bandit                            1.7.7
bcrypt                            4.2.0
beartype                          0.18.5
beautifulsoup4                    4.12.3
bitsandbytes                      0.43.3
bleach                            6.1.0
blinker                           1.8.2
blis                              0.7.11
boto3                             1.34.162
botocore                          1.34.162
braceexpand                       0.1.7
bs4                               0.0.2
build                             1.1.1
bypy                              1.8.4
cachetools                        5.3.2
catalogue                         2.0.10
certifi                           2023.11.17
cffi                              1.16.0
cfgv                              3.4.0
chardet                           5.2.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpathlib                      0.16.0
cloudpickle                       3.0.0
cmake                             3.28.1
colorama                          0.4.6
colored                           2.2.4
coloredlogs                       15.0.1
colossalai                        0.4.0
comm                              0.2.1
confection                        0.1.4
contexttimer                      0.3.3
contourpy                         1.2.0
coverage                          7.4.4
cpm-kernels                       1.0.11
cryptacular                       1.6.2
cryptography                      43.0.0
cubinlinker                       0.3.0+2.g405ac64
cuda-python                       12.2.0
cudf                              23.12.0
cugraph                           23.12.0
cugraph-dgl                       23.12.0
cugraph-service-client            23.12.0
cugraph-service-server            23.12.0
cuml                              23.12.0
cupy-cuda12x                      12.3.0
cxxfilt                           0.3.0
cycler                            0.12.1
cymem                             2.0.8
Cython                            3.0.8
dask                              2023.11.0
dask-cuda                         23.12.0
dask-cudf                         23.12.0
DataProperty                      1.0.1
datasets                          2.18.0
dbus-python                       1.2.18
debugpy                           1.8.0
decorator                         5.1.1
deepspeed                         0.14.5
defusedxml                        0.7.1
Deprecated                        1.2.14
diffusers                         0.30.0
dill                              0.3.8
diskcache                         5.6.3
distlib                           0.3.8
distributed                       2023.11.0
distro                            1.7.0
dm-tree                           0.1.8
docker-pycreds                    0.4.0
einops                            0.7.0
evaluate                          0.4.1
exceptiongroup                    1.2.0
execnet                           2.0.2
executing                         2.0.1
expecttest                        0.1.3
fabric                            3.2.2
fastapi                           0.110.0
fastjsonschema                    2.19.1
fastrlock                         0.8.2
fastt5                            0.1.4               /home/fastT5
ffmpy                             0.3.2
filelock                          3.13.1
flash-attn                        2.6.3
flatbuffers                       24.3.25
fonttools                         4.47.2
frozenlist                        1.4.1
fschat                            0.2.36              /home/jiaml/FastChat
fsspec                            2023.12.2
ftfy                              6.2.3
galore-torch                      1.0
gast                              0.5.4
gitdb                             4.0.11
GitPython                         3.1.43
google                            3.0.0
google-auth                       2.26.2
google-auth-oauthlib              0.4.6
gradio                            4.40.0
gradio_client                     1.2.0
graphsurgeon                      0.4.6
graphviz                          0.20.3
greenlet                          3.0.3
grpcio                            1.60.0
h11                               0.14.0
h5py                              3.10.0
hf_transfer                       0.1.6
hjson                             3.1.0
httpcore                          1.0.5
httptools                         0.6.1
httpx                             0.27.0
huggingface-hub                   0.23.2
humanfriendly                     10.0
hupper                            1.12.1
hypothesis                        5.35.1
identify                          2.5.35
idna                              3.6
imageio                           2.34.2
imageio-ffmpeg                    0.5.1
importlib-metadata                7.0.1
importlib_resources               6.4.0
iniconfig                         2.0.0
intel-openmp                      2021.4.0
interegular                       0.3.3
invoke                            2.2.0
ipykernel                         6.29.5
ipython                           8.20.0
ipython-genutils                  0.2.0
ipywidgets                        8.1.5
janus                             1.0.0
jedi                              0.19.1
Jinja2                            3.1.3
jiter                             0.5.0
jmespath                          1.0.1
joblib                            1.3.2
json5                             0.9.14
jsonlines                         4.0.0
jsonschema                        4.21.1
jsonschema-specifications         2023.12.1
jupyter_client                    8.6.0
jupyter_core                      5.7.1
jupyter-tensorboard               0.2.0
jupyterlab                        2.3.2
jupyterlab_pygments               0.3.0
jupyterlab-server                 1.2.0
jupyterlab_widgets                3.0.13
jupytext                          1.16.1
kiwisolver                        1.4.5
langcodes                         3.3.0
lark                              1.1.9
lazy_loader                       0.3
librosa                           0.10.1
lit                               18.1.8
llvmlite                          0.40.1
lm_eval                           0.4.2
lm-format-enforcer                0.10.3
locket                            1.0.0
lxml                              5.1.0
Mako                              1.3.5
Markdown                          3.5.2
markdown-it-py                    3.0.0
markdown2                         2.4.13
MarkupSafe                        2.1.4
matplotlib                        3.8.2
matplotlib-inline                 0.1.6
mbstrdecoder                      1.1.3
mdit-py-plugins                   0.4.0
mdurl                             0.1.2
mistune                           3.0.2
mkl                               2021.1.1
mkl-devel                         2021.1.1
mkl-include                       2021.1.1
mmengine                          0.10.4
mock                              5.1.0
more-itertools                    10.2.0
moviepy                           1.0.3
mpi4py                            3.1.5
mpmath                            1.3.0
msgpack                           1.0.7
multidict                         6.0.4
multiprocess                      0.70.16
murmurhash                        1.0.10
mypy                              1.9.0
mypy-extensions                   1.0.0
nbclient                          0.9.0
nbconvert                         7.14.2
nbformat                          5.9.2
nest-asyncio                      1.5.9
networkx                          2.6.3
nh3                               0.2.17
ninja                             1.11.1.1
nltk                              3.8.1
nodeenv                           1.8.0
notebook                          6.4.10
numba                             0.57.1+1.g1ff679645
numexpr                           2.9.0
numpy                             1.24.4
nvfuser                           0.1.1+gitunknown
nvidia-ammo                       0.7.4
nvidia-cublas-cu11                11.10.3.66
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu11            11.7.101
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu11            11.7.99
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu11          11.7.99
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu11                 8.5.0.96
nvidia-cudnn-cu12                 8.9.2.26
nvidia-cufft-cu11                 10.9.0.58
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu11                10.2.10.91
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu11              11.4.0.1
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu11              11.7.4.91
nvidia-cusparse-cu12              12.1.0.106
nvidia-dali-cuda120               1.33.0
nvidia-ml-py                      12.550.52
nvidia-nccl-cu11                  2.14.3
nvidia-nccl-cu12                  2.19.3
nvidia-nvjitlink-cu12             12.4.99
nvidia-nvtx-cu11                  11.7.91
nvidia-nvtx-cu12                  12.1.105
nvidia-pyindex                    1.0.9
nvtx                              0.2.5
oauthlib                          3.2.2
omegaconf                         2.3.0
onnx                              1.15.0rc2
onnx-graphsurgeon                 0.3.27
onnxconverter-common              1.14.0
onnxruntime                       1.16.3
onnxruntime-gpu                   1.19.0
onnxruntime-tools                 1.7.0
openai                            1.40.6
opencv-contrib-python             4.7.0.72
opencv-python                     4.7.0.72
opensora                          1.2.0
optimum                           1.18.0
optree                            0.10.0
orjson                            3.10.3
outlines                          0.0.46
packaging                         23.2
pandarallel                       1.6.5
pandas                            2.2.2
pandocfilters                     1.5.1
parameterized                     0.9.0
paramiko                          3.4.1
parso                             0.8.3
partd                             1.4.1
PasteDeploy                       3.1.0
pathvalidate                      3.2.0
pbkdf2                            1.3
pbr                               6.0.0
peft                              0.13.2
pexpect                           4.9.0
Pillow                            9.5.0
pip                               24.2
plaster                           1.1.2
plaster-pastedeploy               1.0.1
platformdirs                      4.1.0
pluggy                            1.3.0
plumbum                           1.8.3
ply                               3.11
polygraphy                        0.49.1
pooch                             1.8.0
portalocker                       2.8.2
pre-commit                        3.7.0
preshed                           3.0.9
prettytable                       3.9.0
proglog                           0.1.10
progress                          1.6
prometheus-client                 0.19.0
prometheus-fastapi-instrumentator 7.0.0
prompt-toolkit                    3.0.43
protobuf                          3.20.2
psutil                            5.9.4
ptxcompiler                       0.8.1+2.g0d406d6
ptyprocess                        0.7.0
PuLP                              2.8.0
pure-eval                         0.2.2
py                                1.11.0
py-cpuinfo                        9.0.0
py3nvml                           0.2.7
pyairports                        2.1.1
pyarrow                           17.0.0
pyarrow-hotfix                    0.6
pyasn1                            0.5.1
pyasn1-modules                    0.3.0
pybind11                          2.11.1
pybind11-global                   2.11.1
pybind11-stubgen                  2.5
pycocotools                       2.0+nv0.8.0
pycountry                         24.6.1
pycparser                         2.21
pycuda                            2024.1.2
pydantic                          2.7.3
pydantic_core                     2.18.4
pydantic-settings                 2.3.0
pydeck                            0.9.1
pydub                             0.25.1
Pygments                          2.17.2
PyGObject                         3.42.1
pylibcugraph                      23.12.0
pylibcugraphops                   23.12.0
pylibraft                         23.12.0
PyNaCl                            1.5.0
pynvml                            11.5.0
pyparsing                         3.1.1
pyproject                         1.3.1
pyproject_hooks                   1.0.0
pyramid                           2.0.2
pyramid-mailer                    0.15.1
pytablewriter                     1.2.0
pytest                            7.4.4
pytest-cov                        5.0.0
pytest-flakefinder                1.1.0
pytest-forked                     1.6.0
pytest-rerunfailures              13.0
pytest-shard                      0.1.2
pytest-xdist                      3.5.0
python-dateutil                   2.8.2
python-dotenv                     1.0.1
python-hostlist                   1.23.0
python-multipart                  0.0.9
python3-openid                    3.2.0
pytools                           2024.1.13
pytorch-quantization              2.1.2
pytz                              2023.3.post1
PyYAML                            6.0.1
pyzmq                             25.1.2
raft-dask                         23.12.0
rapids-dask-dependency            23.12.1
ray                               2.10.0
referencing                       0.32.1
regex                             2023.12.25
repoze.sendmail                   4.4.1
requests                          2.31.0
requests-oauthlib                 1.3.1
requests-toolbelt                 1.0.0
responses                         0.18.0
rich                              13.7.0
rmm                               23.12.0
rotary-embedding-torch            0.5.3
rouge-score                       0.1.2
rpds-py                           0.17.1
rpyc                              6.0.0
rsa                               4.9
ruff                              0.4.7
s3transfer                        0.10.2
sacrebleu                         2.4.1
safetensors                       0.4.5
scikit-learn                      1.2.0
scipy                             1.12.0
semantic-version                  2.10.0
Send2Trash                        1.8.2
sentencepiece                     0.2.0
sentry-sdk                        2.13.0
setproctitle                      1.3.3
setuptools                        68.2.2
shellingham                       1.5.4
shortuuid                         1.0.13
six                               1.16.0
smart-open                        6.4.0
smmap                             5.0.1
sniffio                           1.3.1
sortedcontainers                  2.4.0
soundfile                         0.12.1
soupsieve                         2.5
soxr                              0.3.7
spaces                            0.29.3
spacy                             3.7.2
spacy-legacy                      3.0.12
spacy-loggers                     1.0.5
sphinx-glpi-theme                 0.5
SQLAlchemy                        2.0.32
sqlitedict                        2.1.0
srsly                             2.4.8
stack-data                        0.6.3
starlette                         0.36.3
stevedore                         5.2.0
streamlit                         1.37.0
StrEnum                           0.4.15
svgwrite                          1.4.3
SwissArmyTransformer              0.4.12
sympy                             1.12
tabledata                         1.3.3
tabulate                          0.9.0
tbb                               2021.11.0
tblib                             3.0.0
tcolorpy                          0.1.4
tenacity                          8.5.0
tensorboard                       2.17.1
tensorboard-data-server           0.7.2
tensorboard-plugin-wit            1.8.1
tensorboardX                      2.6.2.2
tensorrt                          9.2.0.post12.dev5
tensorrt-bindings                 9.2.0.post12.dev5
tensorrt-libs                     9.2.0.post12.dev5
tensorrt-llm                      0.8.0
termcolor                         2.4.0
terminado                         0.18.0
tf2onnx                           1.16.1
thinc                             8.2.2
threadpoolctl                     3.2.0
thriftpy2                         0.4.17
tiktoken                          0.6.0
timm                              0.9.16
tinycss2                          1.2.1
tokenizers                        0.15.2
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.12.0
toolz                             0.12.1
torch                             2.2.2
torch-tensorrt                    2.2.0a0
torchdata                         0.7.0a0
torchsde                          0.2.6
torchtext                         0.17.0a0
torchvision                       0.17.2
tornado                           6.4
tqdm                              4.66.1
tqdm-multiprocess                 0.0.11
traitlets                         5.9.0
trampoline                        0.1.2
transaction                       4.0
transformers                      4.39.3
translationstring                 1.4
treelite                          3.9.1
treelite-runtime                  3.9.1
triton                            2.2.0
typepy                            1.3.2
typer                             0.12.3
types-dataclasses                 0.6.6
typing_extensions                 4.12.2
tzdata                            2024.1
ucx-py                            0.35.0
uff                               0.6.9
urllib3                           2.2.2
uvicorn                           0.29.0
uvloop                            0.19.0
velruse                           1.1.1
venusian                          3.1.0
videosys                          2.0.0               /home/workspace/TeaCache
virtualenv                        20.25.1
vllm                              0.5.2+cu123         /home/vllm_glm4v/vllm-glm4v
vllm-flash-attn                   2.5.9.post1
wandb                             0.17.7
wasabi                            1.1.2
watchdog                          4.0.2
watchfiles                        0.21.0
wavedrom                          2.0.3.post3
wcwidth                           0.2.13
weasel                            0.3.4
webdataset                        0.2.96
webencodings                      0.5.1
WebOb                             1.8.8
websockets                        11.0.3
Werkzeug                          3.0.1
wheel                             0.42.0
widgetsnbextension                4.0.13
word2number                       1.1
wrapt                             1.16.0
WTForms                           3.1.2
wtforms-recaptcha                 0.3.2
xdoctest                          1.0.2
xformers                          0.0.25.post1
xgboost                           1.7.6
xmltodict                         0.13.0
xxhash                            3.4.1
yapf                              0.40.2
yarl                              1.9.4
zict                              3.0.0
zipp                              3.17.0
zope.deprecation                  5.0
zope.interface                    7.0.1
zope.sqlalchemy                   3.1
zstandard                         0.22.0

**Comment by LiewFeng** [comment]
Sorry, it's a typo. Replace 'egine.driver_worker.transformer.__class__.__class__.forward = teacache_forward' with 'gine.driver_worker.transformer.__class__.forward = teacache_forward' in opensora.py should work. I will fix it later.

**Comment by Jamrainbow** [comment]
> Sorry, it's a typo. Replace 'egine.driver_worker.transformer.**class**.**class**.forward = teacache_forward' with 'gine.driver_worker.transformer.**class**.forward = teacache_forward' in opensora.py should work. I will fix it later.

thanks,it works.
is it support two gpus?
when i set num_gpus=2.i got stuck 
the error is below

[E ProcessGroupNCCL.cpp:475] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLTOALL, NumelIn=29030400, NumelOut=29030400, Timeout(ms)=1800000) ran for 1800404 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLTOALL, NumelIn=29030400, NumelOut=29030400, Timeout(ms)=1800000) ran for 1800404 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLTOALL, NumelIn=29030400, NumelOut=29030400, Timeout(ms)=1800000) ran for 1800404 milliseconds before timing out.
/opt/conda/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 7 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[E ProcessGroupNCCL.cpp:475] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLGATHER, NumelIn=58060800, NumelOut=116121600, Timeout(ms)=1800000) ran for 1800073 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLTOALL, NumelIn=29030400, NumelOut=29030400, Timeout(ms)=1800000) ran for 1800629 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLGATHER, NumelIn=58060800, NumelOut=116121600, Timeout(ms)=1800000) ran for 1800073 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLGATHER, NumelIn=58060800, NumelOut=116121600, Timeout(ms)=1800000) ran for 1800073 milliseconds before timing out.
Aborted (core dumped)
root@nf5468m7-36:/home/workspace/TeaCache/eval/teacache# [E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLTOALL, NumelIn=29030400, NumelOut=29030400, Timeout(ms)=1800000) ran for 1800629 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=58, OpType=ALLTOALL, NumelIn=29030400, NumelOut=29030400, Timeout(ms)=1800000) ran for 1800629 milliseconds before timing out.
/opt/conda/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 7 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by LiewFeng** [comment]
For multi-gpu inference, you can replace the foward function and set the hyperparameters inside the STDiT3 module.
