### ISSUE TITLE
How to get coefficients?

### ISSUE THREAD

**Issue by moclimb** [LiewFeng/TeaCache#2]
<img width="795" alt="image" src="https://github.com/user-attachments/assets/d02beb05-aab8-454c-bdcc-7def049ba966">

I found that each coefficients in different model is different, so how to get the value? Is there some tricks?

**Comment by LiewFeng** [comment]
To obtain robust polynomial fitting, we sample 70 texts from T2V-CompBench to generate videos, assessing seven desired attributes of generated videos. 10 prompts are sampled for each attributes. Afetr obtaining the timestep embedding modulated noisy input and model output with these text prompts, it can be efficiently solved using the poly1d function from the numpy package.

**Comment by liangbo99** [comment]
> To obtain robust polynomial fitting, we sample 70 texts from T2V-CompBench to generate videos, assessing seven desired attributes of generated videos. 10 prompts are sampled for each attributes. Afetr obtaining the timestep embedding modulated noisy input and model output with these text prompts, it can be efficiently solved using the poly1d function from the numpy package.

The function is `np.polyfit(x, y, 4)`? where x is  timestep embedding modulated noisy input, y is model output?

**Comment by LiewFeng** [comment]
yep!

**Comment by moclimb** [comment]
Thank you for your reply!! I will try it!!!

**Comment by littletomatodonkey** [comment]
Hi @LiewFeng are all steps' inputs and outputs are used for fitting process? For example, if the denoise step is 50,  are all the 50  inputs and outputs will be used? Thanks!

**Comment by LiewFeng** [comment]
Hi, @littletomatodonkey yep!

**Comment by littletomatodonkey** [comment]
> > To obtain robust polynomial fitting, we sample 70 texts from T2V-CompBench to generate videos, assessing seven desired attributes of generated videos. 10 prompts are sampled for each attributes. Afetr obtaining the timestep embedding modulated noisy input and model output with these text prompts, it can be efficiently solved using the poly1d function from the numpy package.
> 
> The function is `np.polyfit(x, y, 4)`? where x is timestep embedding modulated noisy input, y is model output?

![image](https://github.com/user-attachments/assets/e180ace7-2374-4ead-8006-7f460c327be2)
Hi @liangbo99 According to the paper's desc, it seems that input difference are used for the fitting rather than the input?

**Comment by LiewFeng** [comment]
Since the output is the ideal indicator for caching or not. We want to reduce the estimation error of modulated input with the fitting.

**Comment by LiewFeng** [comment]
> > > To obtain robust polynomial fitting, we sample 70 texts from T2V-CompBench to generate videos, assessing seven desired attributes of generated videos. 10 prompts are sampled for each attributes. Afetr obtaining the timestep embedding modulated noisy input and model output with these text prompts, it can be efficiently solved using the poly1d function from the numpy package.
> > 
> > 
> > The function is `np.polyfit(x, y, 4)`? where x is timestep embedding modulated noisy input, y is model output?
> 
> ![image](https://private-user-images.githubusercontent.com/14270174/396341346-e180ace7-2374-4ead-8006-7f460c327be2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDY4NzUsIm5iZiI6MTczNDQwNjU3NSwicGF0aCI6Ii8xNDI3MDE3NC8zOTYzNDEzNDYtZTE4MGFjZTctMjM3NC00ZWFkLTgwMDYtN2Y0NjBjMzI3YmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MDY5YjU4ZjU5NjE3ZGJjNTdmMjllNjg1ODEwMWI3MWU2YzI4YWQwOTRjOTQ0YWYyN2JiMDNkZDk3MzIzNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cSSYaW0i0wWDGQgj3GbxZmi5eghUQNZttKN6iq_uLIE) Hi @liangbo99 According to the paper's desc, it seems that input difference are used for the fitting rather than the input?

Yep!

**Comment by littletomatodonkey** [comment]
Hi,  @liangbo99 just for confirmation, for my own model weights, the process is

* collect modulated input diff between 2 steps and output hidden states between 2 steps. (If 50 steps are used, then total 49-pairs of data will be collected for each prompt)
* calculate all pairs diff and use `polyfit` for the fitting process. (Is **Log()** needed for the data process? I saw it in the figure but not in the equation)
* get the coef and use it for the inference.

Is that right? Thanks !

**Comment by LiewFeng** [comment]
1) Relative diff.
2) Log is  not needed. It's only for visualization.

**Comment by littletomatodonkey** [comment]
> 1. Relative diff.
> 2. Log is  not needed. It's only for visualization.

Let me have a try, thanks too much!

**Comment by LiewFeng** [comment]
Hi, @littletomatodonkey .

> But the output hidden states mean diff is always larger than 5, the following curves are prediction and groundtruth (curr_hidden_states_output - previous_hidden_states_output) of 3 prompts.

It should be (curr_hidden_states_output - previous_hidden_states_output) / previous_hidden_states_output

**Comment by littletomatodonkey** [comment]
> Hi, @littletomatodonkey .
> 
> > But the output hidden states mean diff is always larger than 5, the following curves are prediction and groundtruth (curr_hidden_states_output - previous_hidden_states_output) of 3 prompts.
> 
> It should be (curr_hidden_states_output - previous_hidden_states_output) / previous_hidden_states_output

Ok, let me try it today, and i directly used modulated inputs diff as the rule to decide whether to cache and it got 1.73x speedup without obvious quality degrade. Thanks!

**Comment by LiewFeng** [comment]
You can further  adjust the threshould to obtain your desired trade-off between  speedup and visual quality.

**Comment by zishen-ucap** [comment]
> > > > To obtain robust polynomial fitting, we sample 70 texts from T2V-CompBench to generate videos, assessing seven desired attributes of generated videos. 10 prompts are sampled for each attributes. Afetr obtaining the timestep embedding modulated noisy input and model output with these text prompts, it can be efficiently solved using the poly1d function from the numpy package.
> > > 
> > > 
> > > The function is `np.polyfit(x, y, 4)`? where x is timestep embedding modulated noisy input, y is model output?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/14270174/396341346-e180ace7-2374-4ead-8006-7f460c327be2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDY4NzUsIm5iZiI6MTczNDQwNjU3NSwicGF0aCI6Ii8xNDI3MDE3NC8zOTYzNDEzNDYtZTE4MGFjZTctMjM3NC00ZWFkLTgwMDYtN2Y0NjBjMzI3YmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MDY5YjU4ZjU5NjE3ZGJjNTdmMjllNjg1ODEwMWI3MWU2YzI4YWQwOTRjOTQ0YWYyN2JiMDNkZDk3MzIzNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cSSYaW0i0wWDGQgj3GbxZmi5eghUQNZttKN6iq_uLIE) Hi @liangbo99 According to the paper's desc, it seems that input difference are used for the fitting rather than the input?
> 
> Yep!

Is this ouput before or after the self. proj_out operation？

**Comment by liangbo99** [comment]
> > > > > To obtain robust polynomial fitting, we sample 70 texts from T2V-CompBench to generate videos, assessing seven desired attributes of generated videos. 10 prompts are sampled for each attributes. Afetr obtaining the timestep embedding modulated noisy input and model output with these text prompts, it can be efficiently solved using the poly1d function from the numpy package.
> > > > 
> > > > 
> > > > The function is `np.polyfit(x, y, 4)`? where x is timestep embedding modulated noisy input, y is model output?
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/14270174/396341346-e180ace7-2374-4ead-8006-7f460c327be2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDY4NzUsIm5iZiI6MTczNDQwNjU3NSwicGF0aCI6Ii8xNDI3MDE3NC8zOTYzNDEzNDYtZTE4MGFjZTctMjM3NC00ZWFkLTgwMDYtN2Y0NjBjMzI3YmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MDY5YjU4ZjU5NjE3ZGJjNTdmMjllNjg1ODEwMWI3MWU2YzI4YWQwOTRjOTQ0YWYyN2JiMDNkZDk3MzIzNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cSSYaW0i0wWDGQgj3GbxZmi5eghUQNZttKN6iq_uLIE) Hi @liangbo99 According to the paper's desc, it seems that input difference are used for the fitting rather than the input?
> > 
> > 
> > Yep!
> 
> Is this ouput before or after the self. proj_out operation？

I think the output which used is before the  norm and projection layer, but the answer is up to the author~

**Comment by zishen-ucap** [comment]
> > > > > > To obtain robust polynomial fitting, we sample 70 texts from T2V-CompBench to generate videos, assessing seven desired attributes of generated videos. 10 prompts are sampled for each attributes. Afetr obtaining the timestep embedding modulated noisy input and model output with these text prompts, it can be efficiently solved using the poly1d function from the numpy package.
> > > > > 
> > > > > 
> > > > > The function is `np.polyfit(x, y, 4)`? where x is timestep embedding modulated noisy input, y is model output?
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/14270174/396341346-e180ace7-2374-4ead-8006-7f460c327be2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDY4NzUsIm5iZiI6MTczNDQwNjU3NSwicGF0aCI6Ii8xNDI3MDE3NC8zOTYzNDEzNDYtZTE4MGFjZTctMjM3NC00ZWFkLTgwMDYtN2Y0NjBjMzI3YmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MDY5YjU4ZjU5NjE3ZGJjNTdmMjllNjg1ODEwMWI3MWU2YzI4YWQwOTRjOTQ0YWYyN2JiMDNkZDk3MzIzNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cSSYaW0i0wWDGQgj3GbxZmi5eghUQNZttKN6iq_uLIE) Hi @liangbo99 According to the paper's desc, it seems that input difference are used for the fitting rather than the input?
> > > 
> > > 
> > > Yep!
> > 
> > 
> > Is this ouput before or after the self. proj_out operation？
> 
> I think the output which used is before the norm and projection layer, but the answer is up to the author~
![B9CCD39B-D54A-4c31-B098-5BFE498EA5AC](https://github.com/user-attachments/assets/6de6074a-97ba-4ecc-bdab-b0677f244a06)

Is the hidden_states obtained in this step used as y calculation?

**Comment by LiewFeng** [comment]
@zishen-ucap . You can refer to [issue 20](https://github.com/ali-vilab/TeaCache/issues/20).

**Comment by zhujiagang** [comment]
> Hi, [@littletomatodonkey](https://github.com/littletomatodonkey) .
> 
> > But the output hidden states mean diff is always larger than 5, the following curves are prediction and groundtruth (curr_hidden_states_output - previous_hidden_states_output) of 3 prompts.
> 
> It should be (curr_hidden_states_output - previous_hidden_states_output) / previous_hidden_states_output
@LiewFeng 
Thank you for sharing your work. 
I met a question when I want to get the value of output L1 relative distance by
`output_l1 = (((self.previous_residual).abs().mean() / origin_x.abs().mean()).cpu().item())` in opensora, the value is around 13. In MagicDriveDiT, it is around 6. Am I wrong? Should it be less than 1?

**Comment by Justin900429** [comment]
Here’s a simple script I put together to reproduce Figures 3 and 5 and extract the corresponding coefficients, using OpenSora as an example.

```python

import glob
import random
from collections import defaultdict
from functools import partial

import numpy as np
import torch
from einops import rearrange

from videosys import OpenSoraConfig, VideoSysEngine
from videosys.core.comm import gather_sequence, get_pad, set_pad, split_sequence
from videosys.models.transformers.open_sora_transformer_3d import auto_grad_checkpoint, t2i_modulate
from videosys.utils.utils import batch_func

# ===== 1. Create Model =====
config = OpenSoraConfig()
engine = VideoSysEngine(config)

# ===== 2. Forward wrap to get two inputs =====

def wrap_forward(save_modulated_output_dict: dict[int, list[torch.Tensor]], save_output_dict: dict[int, list[torch.Tensor]]):
    def forward(
        self, x, timestep, all_timesteps, y, mask=None, x_mask=None, fps=None, height=None, width=None, **kwargs
    ):
        constant_timestep = int(timestep[0].item())
        # === Split batch ===
        if self.parallel_manager.cp_size > 1:
            x, timestep, y, x_mask, mask = batch_func(
                partial(split_sequence, process_group=self.parallel_manager.cp_group, dim=0),
                x,
                timestep,
                y,
                x_mask,
                mask,
            )

        dtype = self.x_embedder.proj.weight.dtype
        B = x.size(0)
        x = x.to(dtype)
        timestep = timestep.to(dtype)
        y = y.to(dtype)

        # === get pos embed ===
        _, _, Tx, Hx, Wx = x.size()
        T, H, W = self.get_dynamic_size(x)
        S = H * W
        base_size = round(S**0.5)
        resolution_sq = (height[0].item() * width[0].item()) ** 0.5
        scale = resolution_sq / self.input_sq_size
        pos_emb = self.pos_embed(x, H, W, scale=scale, base_size=base_size)

        # === get timestep embed ===
        t = self.t_embedder(timestep, dtype=x.dtype)  # [B, C]
        fps = self.fps_embedder(fps.unsqueeze(1), B)
        t = t + fps
        t_mlp = self.t_block(t)
        t0 = t0_mlp = None
        if x_mask is not None:
            t0_timestep = torch.zeros_like(timestep)
            t0 = self.t_embedder(t0_timestep, dtype=x.dtype)
            t0 = t0 + fps
            t0_mlp = self.t_block(t0)

        # === get y embed ===
        if self.config.skip_y_embedder:
            y_lens = mask
            if isinstance(y_lens, torch.Tensor):
                y_lens = y_lens.long().tolist()
        else:
            y, y_lens = self.encode_text(y, mask)

        # === get x embed ===
        x = self.x_embedder(x)  # [B, N, C]
        x = rearrange(x, "B (T S) C -> B T S C", T=T, S=S)
        x = x + pos_emb
        
        # === get modulate output ===
        inp = x.clone()
        inp = rearrange(inp, "B T S C -> B (T S) C", T=T, S=S)
        B, N, C = inp.shape
        shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp = (
            self.spatial_blocks[0].scale_shift_table[None] + t_mlp.reshape(B, 6, -1)
        ).chunk(6, dim=1)
        modulated_inp = t2i_modulate(self.spatial_blocks[0].norm1(inp), shift_msa, scale_msa)
        save_modulated_output_dict[constant_timestep].append(modulated_inp.cpu())

        # shard over the sequence dim if sp is enabled
        if self.parallel_manager.sp_size > 1:
            set_pad("temporal", T, self.parallel_manager.sp_group)
            set_pad("spatial", S, self.parallel_manager.sp_group)
            x = split_sequence(x, self.parallel_manager.sp_group, dim=1, grad_scale="down", pad=get_pad("temporal"))
            T = x.shape[1]
            x_mask_org = x_mask
            x_mask = split_sequence(
                x_mask, self.parallel_manager.sp_group, dim=1, grad_scale="down", pad=get_pad("temporal")
            )

        x = rearrange(x, "B T S C -> B (T S) C", T=T, S=S)

        # === blocks ===
        for spatial_block, temporal_block in zip(self.spatial_blocks, self.temporal_blocks, strict=True):
            x = auto_grad_checkpoint(
                spatial_block,
                x,
                y,
                t_mlp,
                y_lens,
                x_mask,
                t0_mlp,
                T,
                S,
                timestep,
                all_timesteps=all_timesteps,
            )

            x = auto_grad_checkpoint(
                temporal_block,
                x,
                y,
                t_mlp,
                y_lens,
                x_mask,
                t0_mlp,
                T,
                S,
                timestep,
                all_timesteps=all_timesteps,
            )

        if self.parallel_manager.sp_size > 1:
            x = rearrange(x, "B (T S) C -> B T S C", T=T, S=S)
            x = gather_sequence(x, self.parallel_manager.sp_group, dim=1, grad_scale="up", pad=get_pad("temporal"))
            T, S = x.shape[1], x.shape[2]
            x = rearrange(x, "B T S C -> B (T S) C", T=T, S=S)
            x_mask = x_mask_org
            

        # === final layer ===
        if T is None:
            T = self.final_layer.d_t
        if S is None:
            S = self.final_layer.d_s
        shift, scale = (self.final_layer.scale_shift_table[None] + t[:, None]).chunk(2, dim=1)
        x = t2i_modulate(self.final_layer.norm_final(x), shift, scale)
        if x_mask is not None:
            shift_zero, scale_zero = (self.final_layer.scale_shift_table[None] + t0[:, None]).chunk(2, dim=1)
            x_zero = t2i_modulate(self.final_layer.norm_final(x), shift_zero, scale_zero)
            x = self.final_layer.t_mask_select(x_mask, x, x_zero, T, S)
        save_output_dict[constant_timestep].append(x.cpu().clone())
        x = self.final_layer.linear(x)
        
        x = self.unpatchify(x, T, H, W, Tx, Hx, Wx)

        # cast to float32 for better accuracy
        x = x.to(torch.float32)

        # === Gather Output ===
        if self.parallel_manager.cp_size > 1:
            x = gather_sequence(x, self.parallel_manager.cp_group, dim=0)

        return x
    return forward

save_modulated_output_dict = defaultdict(list)
save_output_dict = defaultdict(list)
engine.driver_worker.transformer.__class__.forward = wrap_forward(save_modulated_output_dict, save_output_dict)

# ===== 3. Randomly select prompts and save intermediate results

prompt_list = []
all_prompts = glob.glob("data/t2v_compbench/prompts/*.txt")
random.seed(42)
for prompt_file in all_prompts:
    with open(prompt_file, "r") as f:
        prompts = f.readlines()
    random_prompts = random.sample(prompts, 10)
    prompt_list.extend([prompt.strip() for prompt in random_prompts])
print(len(prompt_list))

modulated_timestep_all = defaultdict(list)
output_timestep_all = defaultdict(list)

for prompt in prompt_list:
    video = engine.generate(prompt, seed=42)
    timestep_keys = sorted(list(save_output_dict.keys()), reverse=True)

    for timestep_idx in range(1, len(timestep_keys)):
        cur_modulated_output = torch.cat(save_modulated_output_dict[timestep_keys[timestep_idx]], dim=0)
        prev_modulated_output = torch.cat(save_modulated_output_dict[timestep_keys[timestep_idx - 1]], dim=0)
        
        cur_output = torch.cat(save_output_dict[timestep_keys[timestep_idx]], dim=0)
        prev_output = torch.cat(save_output_dict[timestep_keys[timestep_idx - 1]], dim=0)
        
        rel_modulated_diff = (cur_modulated_output - prev_modulated_output).abs().mean() / prev_modulated_output.abs().mean()
        rel_output_diff = (cur_output - prev_output).abs().mean() / prev_output.abs().mean()
        
        modulated_timestep_all[timestep_keys[timestep_idx]].append(rel_modulated_diff.item())
        output_timestep_all[timestep_keys[timestep_idx]].append(rel_output_diff.item())
        
        del cur_modulated_output, prev_modulated_output, cur_output, prev_output, rel_modulated_diff, rel_output_diff
        
    save_modulated_output_dict.clear()
    save_output_dict.clear()

# ===== 4. Show Figure 3 =====

from matplotlib import pyplot as plt

timestep_keys = sorted(list(modulated_timestep_all.keys()), reverse=True)

rel_modulated_diffs = [
    sum(modulated_timestep_all[timestep_key]) / len(modulated_timestep_all[timestep_key]) for timestep_key in timestep_keys
]
rel_output_diffs = [
    sum(output_timestep_all[timestep_key]) / len(output_timestep_all[timestep_key]) for timestep_key in timestep_keys
]
    
plt.plot(rel_modulated_diffs, label="Rel. Modulated Diff")
plt.plot(rel_output_diffs, label="Rel. Output Diff")
plt.legend()
plt.show()
    
# ===== 5. Show Figure 5 =====

coefficients = np.polyfit(rel_modulated_diffs, rel_output_diffs, 4)
print(coefficients)
rescale_func = np.poly1d(coefficients)
pred_rel_output_diffs = rescale_func(rel_modulated_diffs)

# plot y = x line
min_val = np.round(min(np.min(np.log(rel_modulated_diffs)), np.min(np.log(rel_output_diffs)))).astype(int)
max_val = np.round(max(np.max(np.log(rel_modulated_diffs)), np.max(np.log(rel_output_diffs)))).astype(int)
plt.plot(range(min_val + 1, max_val + 1), range(min_val + 1, max_val + 1), label="y = x")

plt.scatter(np.log(rel_modulated_diffs), np.log(rel_output_diffs), label="Original")
plt.scatter(np.log(rel_output_diffs), np.log(pred_rel_output_diffs), label="Rescale")
plt.legend()
plt.show()
```

* Figure 3

<img width="547" height="413" alt="Image" src="https://github.com/user-attachments/assets/dba17f6d-845d-4206-a1f2-f194f5a481ba" />

* Figure 5

<img width="559" height="413" alt="Image" src="https://github.com/user-attachments/assets/22b121ec-da37-46d9-a099-22f4c9c2c28d" />

Hope this helps!
