### ISSUE TITLE
multi-gpus inference failed

### ISSUE THREAD

**Issue by liangbo99** [LiewFeng/TeaCache#3]
I run teacacahe_slow and set `config = OpenSoraConfig(num_gpus=2)`, and report the errors:
`AttributeError: 'STDiT3' object has no attribute 'parallel_manager'`
the error code is:
```if enable_sequence_parallel():
            if self.enable_teacache:
                if should_calc:
                    x = rearrange(x, "B (T S) C -> B T S C", T=T, S=S)
                    self.previous_residual = rearrange(self.previous_residual, "B (T S) C -> B T S C", T=T, S=S)
                    x = gather_sequence(x, self.parallel_manager.sp_group, dim=1, grad_scale="up", pad=get_temporal_pad("temporal"))
                    self.previous_residual = gather_sequence(self.previous_residual, self.parallel_manager.sp_group, dim=1, grad_scale="up", pad=get_temporal_pad("temporal"))
                    T, S = x.shape[1], x.shape[2]
                    x = rearrange(x, "B T S C -> B (T S) C", T=T, S=S)
                    self.previous_residual = rearrange(self.previous_residual, "B T S C -> B (T S) C", T=T, S=S)
                    x_mask = x_mask_org                                 
            else:
                x = rearrange(x, "B (T S) C -> B T S C", T=T, S=S)
                x = gather_sequence(x, self.parallel_manager.sp_group, dim=1, grad_scale="up", pad=get_temporal_pad("temporal"))
                T, S = x.shape[1], x.shape[2]
                x = rearrange(x, "B T S C -> B (T S) C", T=T, S=S)
                x_mask = x_mask_org
  ```

and I try to correct the code to 
```        if enable_sequence_parallel():
            if self.enable_teacache:
                if should_calc:
                    x = rearrange(x, "B (T S) C -> B T S C", T=T, S=S)
                    self.previous_residual = rearrange(self.previous_residual, "B (T S) C -> B T S C", T=T, S=S)
                    x = gather_sequence(x, get_sequence_parallel_group(), dim=1, grad_scale="up", pad=get_temporal_pad())
                    self.previous_residual = gather_sequence(self.previous_residual, get_sequence_parallel_group(), dim=1, grad_scale="up", pad=get_temporal_pad())
                    T, S = x.shape[1], x.shape[2]
                    x = rearrange(x, "B T S C -> B (T S) C", T=T, S=S)
                    self.previous_residual = rearrange(self.previous_residual, "B T S C -> B (T S) C", T=T, S=S)
                    x_mask = x_mask_org                                 
            else:
                x = rearrange(x, "B (T S) C -> B T S C", T=T, S=S)
                x = gather_sequence(x, get_sequence_parallel_group(), dim=1, grad_scale="up", pad=get_temporal_pad())
                T, S = x.shape[1], x.shape[2]
                x = rearrange(x, "B T S C -> B (T S) C", T=T, S=S)
                x_mask = x_mask_org
```

but it can only goes one step, and then stucks.

So, how to achieve multi-gpus inference? thanks!

**Comment by LiewFeng** [comment]
For multi-gpus inference, you may try to replace the forward function in STDiT3 module.

**Comment by liangbo99** [comment]
> For multi-gpus inference, you may try to replace the forward function in STDiT3 module.

thank you for reply, I replace the `STDiT3.forward` in `TeaCache/videosys/models/transformers/open_sora_transformer_3d.py` with `teacache_forward` in `TeaCache-main/eval/teacache/experiments/opensora.py` ，but it still stucked. following is output:
```
python experiments/opensora.py 
[12/12/24 06:25:08] INFO     VideoSys - INFO: Init parallel manager with dp_size: 1, cp_size: 1, sp_size: 2                                                                                                      
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.14s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.49s/it]
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
(VideoSysWorkerProcess pid=53951) You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
  0%|                                                                                                                                                                                      | 0/2 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                     | 0/30 [00:00<?, ?it/s]

```

as can be seen, the code stop at the first timestep.

**Comment by liangbo99** [comment]
> > For multi-gpus inference, you may try to replace the forward function in STDiT3 module.
> 
> thank you for reply, I replace the `STDiT3.forward` in `TeaCache/videosys/models/transformers/open_sora_transformer_3d.py` with `teacache_forward` in `TeaCache-main/eval/teacache/experiments/opensora.py` ，but it still stucked. following is output:
> 
> ```
> python experiments/opensora.py 
> [12/12/24 06:25:08] INFO     VideoSys - INFO: Init parallel manager with dp_size: 1, cp_size: 1, sp_size: 2                                                                                                      
> Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.14s/it]
> Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.49s/it]
> You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
> (VideoSysWorkerProcess pid=53951) You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
>   0%|                                                                                                                                                                                      | 0/2 [00:00<?, ?it/s]
>   0%|                                                                                                                                                                                     | 0/30 [00:00<?, ?it/s]
> ```
> 
> as can be seen, the code stop at the first timestep.

the script is as follows:
```
def eval_teacache_slow(prompt_list):
    config = OpenSoraConfig(num_gpus=2)
    engine = VideoSysEngine(config)
    engine.driver_worker.transformer.enable_teacache = True
    engine.driver_worker.transformer.rel_l1_thresh = 0.1
    engine.driver_worker.transformer.accumulated_rel_l1_distance = 0
    engine.driver_worker.transformer.previous_modulated_input = None
    engine.driver_worker.transformer.previous_residual = None
    # engine.driver_worker.transformer.__class__.forward = teacache_forward
    generate_func(engine, prompt_list[10:12], "./samples/opensora_teacache_slow", loop=1)
```

**Comment by liangbo99** [comment]
> > > For multi-gpus inference, you may try to replace the forward function in STDiT3 module.
> > 
> > 
> > thank you for reply, I replace the `STDiT3.forward` in `TeaCache/videosys/models/transformers/open_sora_transformer_3d.py` with `teacache_forward` in `TeaCache-main/eval/teacache/experiments/opensora.py` ，but it still stucked. following is output:
> > ```
> > python experiments/opensora.py 
> > [12/12/24 06:25:08] INFO     VideoSys - INFO: Init parallel manager with dp_size: 1, cp_size: 1, sp_size: 2                                                                                                      
> > Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.14s/it]
> > Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.49s/it]
> > You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
> > (VideoSysWorkerProcess pid=53951) You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
> >   0%|                                                                                                                                                                                      | 0/2 [00:00<?, ?it/s]
> >   0%|                                                                                                                                                                                     | 0/30 [00:00<?, ?it/s]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > as can be seen, the code stop at the first timestep.
> 
> the script is as follows:
> 
> ```
> def eval_teacache_slow(prompt_list):
>     config = OpenSoraConfig(num_gpus=2)
>     engine = VideoSysEngine(config)
>     engine.driver_worker.transformer.enable_teacache = True
>     engine.driver_worker.transformer.rel_l1_thresh = 0.1
>     engine.driver_worker.transformer.accumulated_rel_l1_distance = 0
>     engine.driver_worker.transformer.previous_modulated_input = None
>     engine.driver_worker.transformer.previous_residual = None
>     # engine.driver_worker.transformer.__class__.forward = teacache_forward
>     generate_func(engine, prompt_list[10:12], "./samples/opensora_teacache_slow", loop=1)
> ```

the process is done by set hypers in `STDiT3`.

**Comment by liangbo99** [comment]
Another problem, when use multi-gpus inference, the generated video is wrong. whether use `eval_base` or `eval_teacache_slow`.

the video type is : `720p, 9:16, 4s`,  seed is set to `1024`

https://github.com/user-attachments/assets/24a6640e-e109-4e9e-948f-57fe4119457b

**Comment by LiewFeng** [comment]
It't due to the version of VideoSys. I will update the code in a few days. Thank you for reporting it.

**Comment by LiewFeng** [comment]
Hi, @liangbo99. The code is updated. You may try it again.

**Comment by liangbo99** [comment]
> Hi, @liangbo99. The code is updated. You may try it again.

Thanks for your great work! The code works well when applying multi-gpus inference!

**Comment by LiewFeng** [comment]
@Jamrainbow , You can try to set hyper-parameters in TeaCache/videosys/models/transformers/open_sora_transformer_3d.py
