### ISSUE TITLE
is there a plan to support CogvideoX-5B?

### ISSUE THREAD

**Issue by eisneim** [LiewFeng/TeaCache#4]
it would be nice to support CogvideoX-5B

**Comment by LiewFeng** [comment]
Thank you for your interest in our work. I am occupied by other things recently, it may take a long time...

**Comment by LiewFeng** [comment]
Hi, @eisneim. TeaCache currently supports CogVideoX-2B and CogVideoX-5B. You can try it now.

**Comment by liangbo99** [comment]
Hi, @LiewFeng , have you test the time after acceration? There are my experiments:
```
base
100%|████████████████████████████████████| 50/50 [03:17<00:00,  3.95s/it]
teacache
100%|████████████████████████████████████| 50/50 [03:01<00:00,  3.63s/it]
```
Additionally, the model is CogVideoX-5B, the video format is `720x480, 49frames`, the num_inference_steps=50

**Comment by LiewFeng** [comment]
Hi, @liangbo99 . I update the coefficient and you may try it again.

**Comment by LiewFeng** [comment]
Around 1.5x speedup for teacache slow and 2.4x speedup for teacache fast on A800. You can further adjust the threshould to obtain your desired trade-off between speedup and visual quality.

**Comment by liangbo99** [comment]
> Hi, @liangbo99 . I update the coefficient and you may try it again.

The time is speed up to 02:10, great!!! Another question: the input difference is calculated by `emb`,  how about the output difference?

**Comment by LiewFeng** [comment]
We observe that timestep embedding shows stronger correlation with model output than timestep embedding modulated noisy input for CogVideoX, .

**Comment by liangbo99** [comment]
> We observe that timestep embedding shows stronger correlation with model output than timestep embedding modulated noisy input for CogVideoX, .

Thanks for reply, the model outputs are two tensors:`hidden_states` and `encoder_hidden_states`, which represents for image and text embeddings, respectively. 
So, I wonder which embeddings difference are used  for estimating the coefficients?

**Comment by LiewFeng** [comment]
hidden_states.
