### ISSUE TITLE
is there a plan to support HunyuanVideo 13B Model?

### ISSUE THREAD

**Issue by Owen718** [LiewFeng/TeaCache#5]
Great Work!!!
I believe our community needs an effective, play-and-plugin method to accelerate large video generation models.
It would be wonderful to support HunyuanVideo!

**Comment by LiewFeng** [comment]
Thank you for your interest in our work. I may try it, but I cannot guarantee. You can also have a try!

**Comment by Owen718** [comment]
Dear author, thank you for your response. 
I have carefully reviewed the code and the paper, and I noticed that the **### coefficients for the rescale_func** need to be calculated in advance. Could you please provide the code for calculating these coefficients?

**Comment by LiewFeng** [comment]
You may refer to [issue 2](https://github.com/LiewFeng/TeaCache/issues/2). Support for HunyuanVideo will be released in a few days. Please stay tuned.

**Comment by LiewFeng** [comment]
Hi, @Owen718 . Teacache supports HunyuanVideo now. You can try it!

**Comment by Owen718** [comment]
Thanks !
