### ISSUE TITLE
Is this method effective for few-step inference?

### ISSUE THREAD

**Issue by bee992** [LiewFeng/TeaCache#6]
Hi, thanks for your great work!

I noticed that during few-step inference, the out_hidden_states diff ratio is often much higher (e.g., >0.2 or 0.1), likely because each time step covers a larger span in low-step distillation. Have you tested the acceleration performance in such scenarios?

Looking forward to your insights!

**Comment by LiewFeng** [comment]
I haven't tested it on distilled models. For distilled models, the speedup ratio of teacache should be far smaller than that on the original models but i'm not sure about it. You may adjust the threshold and have a try!
