### ISSUE TITLE
Is it possible to support I2V or IPT2V models instead of T2V？

### ISSUE THREAD

**Issue by 963658029** [LiewFeng/TeaCache#7]
Great Work!!!
It would be wonderful to support some I2V or IPT2V models, etc, ConsisID-Preview, it's based on CogVideoX-5B! It seems that the calculation of coefficients only requires plain text input, while I2V and IPT2V may have images as input. Is it possible to support the latter?

**Comment by LiewFeng** [comment]
Hi, @963658029 . Thank you for your interest in our work. TeaCache4CogVideoX leverages the difference of timestep embedding to estimate the difference of model output. You can try to transfer the coefficients directly. If it doesn't work well, please tell me.

**Comment by 963658029** [comment]
what about ruyi model, it's a I2V model, and based on easyanimate, how to abtain its coefficients? (through easyanimate?)

**Comment by LiewFeng** [comment]
You may refer to [issue 2](https://github.com/LiewFeng/TeaCache/issues/2).

**Comment by LiewFeng** [comment]
Hi, @963658029 . TeaCache supports ConsisID now. See [here](https://github.com/LiewFeng/TeaCache/tree/main/TeaCache4ConsisID). Thanks @SHYuanBest .

**Comment by 963658029** [comment]
Awesome!



---Original---
From: "Feng ***@***.***&gt;
Date: Thu, Dec 26, 2024 21:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LiewFeng/TeaCache] Is it possible to support I2V or IPT2V models instead of T2V？ (Issue #7)




 
Hi, @963658029 . TeaCache supports ConsisID now. See here. Thanks @SHYuanBest .
